name: JSON-RPC Relay CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: hashgraph/hedera-json-rpc-relay
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Build Relay
        run: npm run build

      - name: Create .env File
        env:
          CHAIN_ID: 0x12a
          MIRROR_NODE_URL: https://testnet.hashio.io/api
          HEDERA_NETWORK: testnet
          OPERATOR_ID_MAIN: ${{ secrets.OPERATOR_ID }}
          OPERATOR_KEY_MAIN: ${{ secrets.OPERATOR_KEY }}
        run: |
          echo "CHAIN_ID=${CHAIN_ID}" > .env
          echo "MIRROR_NODE_URL=${MIRROR_NODE_URL}" >> .env
          echo "HEDERA_NETWORK=${HEDERA_NETWORK}" >> .env
          echo "OPERATOR_ID_MAIN=${OPERATOR_ID_MAIN}" >> .env
          echo "OPERATOR_KEY_MAIN=${OPERATOR_KEY_MAIN}" >> .env

      - name: Install and Start Redis
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          sudo systemctl start redis-server
          redis-cli ping

      - name: Start Relay Server
        run: |
          npm run start &
          sleep 5

      - name: Wait for Relay Server to be Ready
        run: |
          echo "Waiting for the Relay server to be ready..."
          for i in {1..10}; do
            RESPONSE=$(curl -s -X POST http://localhost:7546 \
              -H "Content-Type: application/json" \
              -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}')
            if [ -n "$RESPONSE" ] && echo "$RESPONSE" | grep -q "result"; then
              echo "Server is ready: $RESPONSE"
              exit 0
            fi
            echo "Attempt $i: no valid response yet, waiting..."
            sleep 3
          done
          echo "Relay server did not start in time."
          exit 1

      - name: Test Relay Connection
        run: |
          curl -v -X POST http://localhost:7546 \
            -H "Content-Type: application/json" \
            -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}'
